# Virtual Hosts
## Uncomment virtual host import file  
Include conf/extra/httpd-vhosts.conf

## in httpd-vhosts.conf

<VirtualHost *:8080>
    ServerName mysite1.cmpt372.com
    DocumentRoot "C:/sites/site1"
    CustomLog "logs/site1-access.log" common
    <Directory "C:/sites/site1">
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require local
        DirectoryIndex site1.html
    </Directory>
</VirtualHost>

<VirtualHost *:8080>
    ServerName mysite2.cmpt372.com
    DocumentRoot "C:/sites/site2"
    CustomLog "logs/site2-access.log" common
    <Directory "C:/sites/site2">
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require local
    </Directory>
</VirtualHost>

## /sites/site2/.htaccess

Options +Indexes
AuthType Basic
AuthBasicProvider file
AuthName "Restricted Area"
AuthUserFile "C:/sites/.htpasswd"
Require user bobbyc

## create .htpasswd file using command:

htpasswd -c C:/sites/.htpasswd bobbyc