# Custom logging

http {
    log_format_custom_json escape=json '{'
        '"time_local":"$time_local",'
        '"remote_addr":"$remote_addr",'
        '"remote_user":"$remote_user",'
        '"request":"$request",'
        '"status": "$status",'
        '"body_bytes_sent":"$body_bytes_sent",'
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
    '}';
}

# Custom error pages 404, 502

server {
    # assume proxy pass set up
    proxy intercept_errors on;
    error_page 404 /custom_404.html;
    error_page 500 502 503 /custom_50x.html;

    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
    location = /custom_50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}